server:
  port: 3003
spring:
  application:
    name: demo-consumer-feign
    
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
  client:
    serviceUrl:
#      defaultZone: http://eureka.iabc.io:1024/eureka/
      defaultZone: http://eureka-service-stable.guahao-test.com/eureka
    register-with-eureka: true
    fetch-registry: true 
    healthcheck:
      enabled: true
    
#logging:
#  level:
#    com:
#      netflix:
#        eureka: off
#        discovery: off 